import {
  Activity,
  Archive,
  Banknote,
  BookOpen,
  CalendarClock,
  CheckSquare,
  ClipboardList,
  Cpu,
  FileBarChart,
  GitBranch,
  GraduationCap,
  HelpCircle,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  ListFilter,
  Megaphone,
  Network,
  Receipt,
  Settings,
  Shield,
  Sparkles,
  Target,
  Trash2,
  Trophy,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

/** Sidebar icon per route `path` (empty string = dashboard home). */
const BY_PATH: Record<string, LucideIcon> = {
  '': LayoutDashboard,
  'work/leads': Users,
  'work/workboard': LayoutGrid,
  'work/follow-ups': CalendarClock,
  'work/retarget': Target,
  'work/lead-flow': GitBranch,
  'work/archived': Archive,
  'work/add-lead': UserPlus,
  'work/lead-pool': ListFilter,
  'work/lead-pool-admin': Shield,
  'work/recycle-bin': Trash2,
  intelligence: Sparkles,
  'team/members': UsersRound,
  'team/reports': FileBarChart,
  'team/approvals': CheckSquare,
  'team/enrollment-approvals': Banknote,
  'team/my-team': Users,
  'system/training': BookOpen,
  'system/decision-engine': Cpu,
  'system/coaching': GraduationCap,
  'analytics/activity-log': Activity,
  'analytics/day-2-report': LineChart,
  'finance/recharges': Receipt,
  'finance/wallet': Wallet,
  'other/leaderboard': Trophy,
  'other/notice-board': Megaphone,
  'other/live-session': Video,
  'other/daily-report': ClipboardList,
  'settings/app': Settings,
  'settings/help': HelpCircle,
  'settings/org-tree': Network,
}

export function getDashboardNavIcon(path: string): LucideIcon {
  return BY_PATH[path] ?? LayoutGrid
}
